### PR TITLE
Stylize budget tab to be like an accounting report

### PR DESCRIPTION
**Pull request by Nivaturimika**
- use () for negative numbers
- colour every number, in dark tones of course :)

### CODE REVIEW

**Comment by schombert** [comment]
(...) for negative numbers is something that only appears in certain locales. It isn't a thing for US English

**Comment by Nivaturimika** [comment]
> (...) for negative numbers is something that only appears in certain locales. It isn't a thing for US English

this isn't because of language, this is for the accounting LARP, trust me

**Comment by schombert** [comment]
no, see for example https://learn.microsoft.com/en-us/windows/win32/intl/locale-ineg-constants

**Comment by Nivaturimika** [comment]
> no, see for example https://learn.microsoft.com/en-us/windows/win32/intl/locale-ineg-constants

this is the same reason like why vanilla uses diacritics... on the english language
it's for immersion and gameplay stuff, not for usefulness
just trust me it's a good addition that some players will appreciate

**Comment by schombert** [comment]
poll the discord

**Pull request merged**
