### PR TITLE
Stop doxxing people with computer name

### PR DESCRIPTION
**Pull request by wxwisiasdf**

### CODE REVIEW

**Comment by schombert** [comment]
can't people just change it if they want?

**Comment by wxwisiasdf** [comment]
> can't people just change it if they want?

5 people got accidentally doxxed because they didnt notice it

**Comment by schombert** [comment]
meh. someone finding out your computer's name because you are unable to read the text box next to where you entered the ip ... not a concern

**Comment by wxwisiasdf** [comment]
> meh. someone finding out your computer's name because you are unable to read the text box next to where you entered the ip ... not a concern

it is

**Pull request closed without merging**
