### PR TITLE
Macro builder version one point oh

### PR DESCRIPTION
**Pull request by wxwisiasdf**

### CODE REVIEW

**Comment by schombert** [comment]
I see an issue here: your file can have at most 256 templates in it, ever. Which may sound like more than enough, but every version of every mod  launched under every different version of alice will need will need its own set of templates. I believe that it will run out of space rather quickly ... and then what?

**Comment by wxwisiasdf** [comment]
> I see an issue here: your file can have at most 256 templates in it, ever. Which may sound like more than enough, but every version of every mod launched under every different version of alice will need will need its own set of templates. I believe that it will run out of space rather quickly ... and then what?

I will expand it to 8192, does that sound kosher?

**Comment by schombert** [comment]
That will make the problem less likely, for certain, but why not just fix it properly? Let every scenario file have its own template save file. This will allow those old template files to be cleaned up with the old scenario files when they are no longer needed, rather than hanging around forever.

**Comment by wxwisiasdf** [comment]
> That will make the problem less likely, for certain, but why not just fix it properly? Let every scenario file have its own template save file. This will allow those old template files to be cleaned up with the old scenario files when they are no longer needed, rather than hanging around forever.

isnt it better to just have every template be in a single file?

**Comment by schombert** [comment]
Sure, that could work too, although opening a file is somewhat time consuming, and it would be less than ideal to have to open all the template files for all the mods to figure out which one was usable.

**Pull request merged**
