### PR TITLE
Stop crashed players from being controlled by AI

### PR DESCRIPTION
**Pull request by wxwisiasdf**

### CODE REVIEW

**Comment by schombert** [comment]
so then how can players leave a game and turn over control to the ai?

**Comment by wxwisiasdf** [comment]
> so then how can players leave a game and turn over control to the ai?

host kicks "dead" nation

**Comment by schombert** [comment]
what about your automated server idea? No host there to do that manually. If a player crashes, they won't send an "i'm leaving" command to the host. If they drop without leaving, the host can close their connection without sending the notify player has left command if they want to keep the slot player controlled until someone else can fill it.

**Comment by wxwisiasdf** [comment]
> what about your automated server idea? No host there to do that manually. If a player crashes, they won't send an "i'm leaving" command to the host. If they drop without leaving, the host can close their connection without sending the notify player has left command if they want to keep the slot player controlled until someone else can fill it.

they can simply be kicked, or the command can set them to "AI" by default if on headless mode

**Comment by schombert** [comment]
I think having to kick any player that leaves is kind of unnecessary busy work. How about adding a bool to say whether the player should be set to AI on leaving in the command?

**Pull request closed without merging**
