### PR TITLE
parser generator only generate prototypes if needed & fix identation

### PR DESCRIPTION
**Pull request by wxwisiasdf**
- only generate function prototypes to reduce redundancies
- fix identation
- a slight comptime increase

### CODE REVIEW

**Comment by schombert** [comment]
What are the benefits of this changes? I am very hesitant to change the parser generator since it seems to be working fine

**Comment by wxwisiasdf** [comment]
Mainly that it stops generating otherwise unnecessary code, it isn't much, but it shaves off around 400 lines of code - which the compiler might like.

**Comment by schombert** [comment]
Have you actually measured a difference with the compiler diagnostics?

**Comment by wxwisiasdf** [comment]
the difference in timings is pretty insignificant and around the 1-10 ms - so the timings most likely got lost in the noise of `-ftime-trace`. not a lot of justification for adding this change however, but it just makes it slightly more readable for others

**Comment by schombert** [comment]
Then it doesn't seem worth it to me. As a general rule of thumb, only mess with things that are already working when you have to

**Pull request closed without merging**
