### PR TITLE
Made devlogs more organized, + added pt translation to all of them

### PR DESCRIPTION
**Pull request by ioliano**
Added translation of Portuguese (Portugal) to all dev "diaries"/logs, organized all logs into Year-Month folder, and put all images inside a specific folder that way, it's more easy to find exactly what you look for if you used Github to read them initally (like I did) where there is no file coloring or anything like that

### CODE REVIEW

**Comment by schombert** [comment]
I think that you would need to change the links on the readme.md landing page as well

**Comment by ioliano** [comment]
Just fixed the readme.md, and added your changes to January file + Translated the new changes (so you can ignore the conflict on your side) and just use my version

**Comment by schombert** [comment]
I'm still working on January (that is why I haven't published it yet). I probably want to add an image in there somewhere ...

**Comment by ioliano** [comment]
Why don't you merge it, and then edit the log from january?

**Comment by schombert** [comment]
Well, as you can see, I have been working on the January update somewhat continuously. Now that it is published, I can turn to fixing our directory structure and figuring out what to do about all the old links.

**Comment by schombert** [comment]
Alright, I think I am about ready to start making the switch to a better directory structure. We are about to start getting some spanish translations and I don't want to have to move those too. Is the translation of Jan ready to go if I move them all into place?

**Comment by ioliano** [comment]
Hi Schombert,

No, your last changes are not in, I will try to have them ready today

**Pull request merged**
