### PR TITLE
set player on AI (with make_ai parameter for command too)

### PR DESCRIPTION
**Pull request by wxwisiasdf**
added make_ai parameter

### CODE REVIEW

**Comment by schombert** [comment]
do clients have no way of notifying the host that they plan to leave and thus being disconnected "gracefully"?

**Comment by wxwisiasdf** [comment]
> do clients have no way of notifying the host that they plan to leave and thus being disconnected "gracefully"?

theycanjustsend a command

**Comment by wxwisiasdf** [comment]
command::notify_player_leaves(state, client.playing_as, true);

**Comment by schombert** [comment]
Yes, but what I meant was, does that command every get sent if a client closes the game normally? (i.e. via closing the window or an esc > exit command)

**Pull request merged**
