### PR TITLE
merge rally point checkboxes will display why no merge rally points s…

### PR DESCRIPTION
**Pull request by Nivaturimika**
…o people stop complaining

### CODE REVIEW

**Comment by schombert** [comment]
encoding of the csv file got messed up

**Comment by schombert** [comment]
not by you

**Comment by schombert** [comment]
When I added the merge, github fkkd the encoding

**Comment by Nivaturimika** [comment]
what do we do

**Comment by schombert** [comment]
roll back my merge and then merge locally so that github doesn't have a chance to mess the text up

**Comment by Nivaturimika** [comment]
Did this fix it?

**Comment by schombert** [comment]
I don't see any changes to the csv file now, so the new text about the buttons being disabled won't be included I think

**Comment by Nivaturimika** [comment]
> I don't see any changes to the csv file now, so the new text about the buttons being disabled won't be included I think

fiuxes

**Pull request merged**
