### PR TITLE
Dynamic localisation for AHMP

### PR DESCRIPTION
**Pull request by Nivaturimika**
in vanilla yoiu can rename states to do this
however thats a terrible trick
i see this more useful for whatever thing we wish to perform :3

### CODE REVIEW

**Comment by Makkkkus** [comment]
This way of adding scripted localisation seems a bit hack-y. [On the forum](https://forum.paradoxplaza.com/forum/threads/grand-jomini-modding-information-manuscript.1170261/) Paradox has a neat article about how different features work, including dynamic description. The main benefit is a cleaner syntax and theoretically endless descriptions.

**Comment by Nivaturimika** [comment]
Doing that would require an overhaul of the existing effect/trigger system -- which will come later on but by then OpenVic would've released v0.1, so not very near at all.

This is the best that we can do with the current infrastructure.

**Comment by Nivaturimika** [comment]
> I see; although I am worried about backwards-compatability if were to change it in the future.

That's a valid concern, however we'll eventually figure things out - afterall AHMP is the only mod at the moment making use of the Alice engine at it's fullest

**Comment by Makkkkus** [comment]
That's reassuring. I think in this case it would be good to add some context around that in the extensions.md file.

**Comment by schombert** [comment]
This seems like a poor way of doing things. First, present a clear use case. Your description in the modding extensions doc seems like it would be better satisfied by just having two events -- one for each case. Once we have some real examples of where an extension is necessary, we can think about the best way to make them work (keeping in mind the document I posted in translations, since they will need to work in that system too). If you really want arbitrary text generation, then you would want to embed a proper scripting language to run when the text is needed. If you want something less, then maybe something less than that can be added

**Comment by schombert** [comment]
I feel like, given how janky this proposed system is, the redundant events are better

**Comment by Nivaturimika** [comment]
> I feel like, given how janky this proposed system is, the redundant events are better

It doesn't affect performance nor hinders any other mechanic EXCEPT just UI flavour... how is this janky?

**Comment by Nivaturimika** [comment]
Have a better system in mind then?

**Comment by Nivaturimika** [comment]
And no I don't mean the new UI, it would be very hard to adapt the existing text to the new format already as-is, unless you provide tools for doing so

**Pull request closed without merging**
