### PR TITLE
add divider to fix colour for event immediate

### PR DESCRIPTION
**Pull request by wxwisiasdf**

### CODE REVIEW

**Comment by schombert** [comment]
what problem are you trying to fix with this?

**Comment by schombert** [comment]
In V2 the description of the effect goes after the main event description, by the way

**Comment by wxwisiasdf** [comment]
> what problem are you trying to fix with this?

colour being fucked because it is set to white and somehow this causes the immediate effect to become white

**Comment by schombert** [comment]
And does it actually fix that? Because I think the tooltip display forces the text to be white

**Pull request closed without merging**
