### PR TITLE
Improve support for various mods

### PR DESCRIPTION
**Pull request by wxwisiasdf**
This should make most of the popular mods work properly - especially some which used heavy resources [MHM moment, GFM moment].

### CODE REVIEW

**Comment by schombert** [comment]
I think it is time to impose some sanity limits: redirect monarchy2 and republic2 inside the parser to the standard monarchy and republic flags. Redirect cosmetic_1, cosmetic_2,  and spare to somewhere sensible.

**Comment by wxwisiasdf** [comment]
> I think it is time to impose some sanity limits: redirect monarchy2 and republic2 inside the parser to the standard monarchy and republic flags. Redirect cosmetic_1, cosmetic_2, and spare to somewhere sensible.

The mods which use monarchy2 and republic2 have them **separate from republic and monarchy**

**Comment by schombert** [comment]
Yes, I understand that, I am just not convinced that it is worth respecting. Would anything important be lost if those alternate monarchy and republic types just had to have the base monarchy and republic flags?

**Comment by schombert** [comment]
I think that "attrition" wouldn't do anything if you added it to a leader trait in the base game. And unless the base game supports it, I am disinclined to add it

**Comment by schombert** [comment]
The same goes for adding extra unit stats

**Comment by wxwisiasdf** [comment]
Attrition is supported as a trait modifier in the base game iirc.

**Comment by wxwisiasdf** [comment]
We can live without TCG support for now...

**Pull request closed without merging**
