### PR TITLE
allow work for non-avx2 compilations

### PR DESCRIPTION
**Pull request by wxwisiasdf**

### CODE REVIEW

**Comment by schombert** [comment]
this looks like you are trying to support 32bit, which I am definitely not interested in

**Comment by wxwisiasdf** [comment]
> this looks like you are trying to support 32bit, which I am definitely not interested in

looks like doesnt mean it is

**Comment by schombert** [comment]
Ok, then why the changes to detect WIN32 and casting things to size_t?

**Comment by wxwisiasdf** [comment]
> Ok, then why the changes to detect WIN32 and casting things to size_t?

😭

**Comment by schombert** [comment]
You don't have to sob, I just want to understand why the changes are being made

**Comment by wxwisiasdf** [comment]
the most easy way for me to ensure a non-AVX2 can be done, is allowing alice to be compiled on 32-bit; so i can check for stray intrinsics

**Comment by schombert** [comment]
The problem doesn't appear to be stray intrinsics. It looks like the library implementation of one of the atomic functions uses an AVX instruction to me

**Pull request closed without merging**
