### PR TITLE
Away from cursor panning option

### PR DESCRIPTION
**Pull request by Nivaturimika**

### CODE REVIEW

**Comment by schombert** [comment]
away from cursor is an option that no sane person would want, as far as I can tell

**Comment by Nivaturimika** [comment]
> away from cursor is an option that no sane person would want, as far as I can tell

oh gee you never know!

**Comment by Nivaturimika** [comment]
also this pr fixes to_cursor

**Comment by schombert** [comment]
its fine to fix it, but don't add a setting that someone will accidentally set and then complain to us about

**Pull request merged**
